---
- name: deploy-site
  hosts: site
  tasks:
    - name: "Pull in latest changes"
      shell:
        cmd: git pull origin master
        chdir: /home/main/aviddev/

    - name: "Install new packages"
      pip:
        requirements: /home/main/aviddev/requirements.txt
        virtualenv: /home/main/aviddev/env/

    - name: "Collect static files"
      shell:
        cmd: env/bin/python manage.py collectstatic --noinput --settings=mysite.local_settings
        chdir: /home/main/aviddev/

    - name: "Run migrations"
      shell:
        cmd: env/bin/python manage.py migrate --noinput --settings=mysite.local_settings
        chdir: /home/main/aviddev/

    - name: "Reload service"
      systemd:
        name: gunicorn-aviddev
        state: reloaded
